In [26]:
import numpy as np

In [27]:
l = [2,10,12]

In [28]:
a = np.array(l)

In [29]:
a

array([ 2, 10, 12])

In [30]:
m = [[2,4,6], [1,3,5], [7,8,9]]

In [31]:
mat = np.array(m)
mat

array([[2, 4, 6],
       [1, 3, 5],
       [7, 8, 9]])

In [34]:
N = 8
y = np.zeros(N)

np.linspace(0, 100, N)

array([   0.        ,   14.28571429,   28.57142857,   42.85714286,
         57.14285714,   71.42857143,   85.71428571,  100.        ])

In [41]:
np.random.rand(5)

array([ 0.30088145,  0.92177498,  0.7893367 ,  0.13103267,  0.8618731 ])

In [42]:
np.random.randn(5)

array([-2.1780811 , -0.45237739,  0.25080535,  1.31356473, -0.74408059])

In [57]:
0.25 +650.25+132.25+552.25+132.25+5402.25

6869.5

In [58]:
6869.5 / 7

981.3571428571429